spring:
  datasource:
    url: jdbc:mysql://localhost:52000/jwt_security
    username: root
    password: techd
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
